feat(): add validation interceptor
seedium/nestjs-validation pull request #5
Opened 2020-12-24 15:36 UTC by n1ghtm6r9

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2020-12-24 15:50 UTC, KostyaZgara commented on package.json
> +    "rxjs": "^6.6.3"
это должно быть в peer dependencies и dev dependencies

2020-12-24 15:50 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +export class ValidationInterceptor implements NestInterceptor {
название класса всегда должно быть как и название файла

2020-12-24 15:50 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    // добавляем схемы ajv.addSchema(schema)
я же уже писал тебе, искать декораторы надо не в intercerptor-е, он же будет вызываться каждый раз когда будет приходить реквест

2020-12-24 15:50 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    // ключи - имя_контролера_имя_метода_{body,query,headers...}
Подумай лучше как можно связать роут с схемами. Мне дико не нравится этот подход с ключами. Я лишь привел его в пример как крайний случай, есть чувство, что это можно сделать красивее. Возможно в `ValidationModule` сохранять метаданные контроллера и тогда делать что-то типо `this.getSchema(UserController.list)`. Вот так вот было бы очень круто! Или хотя бы вот так вот `this.getSchema(UserController, 'list')`

2020-12-24 15:54 UTC, n1ghtm6r9 commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    // добавляем схемы ajv.addSchema(schema)
там каждый раз новый экземпляр класса будет вызываться? для этого я сделал переменную isSchemeInitialized

2020-12-24 15:56 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    // добавляем схемы ajv.addSchema(schema)
какой новый экземпляр класса? Так, короче, начинай читать отсюда https://docs.nestjs.com/ как работает ядро nestjs

2020-12-28 08:56 UTC, KostyaZgara requested changes

2020-12-28 08:56 UTC, KostyaZgara commented on lib/index.ts
> +export * from './interceptors/json-schema-serializer.interceptor';
В папке `interceptors` надо создать `index.ts` и там экспортировать все содержимое папки. А здесь надо просто будет экспортировать эту папку

```suggestion
export * from './interceptors';
```

2020-12-28 08:56 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +  protected _ajv: Ajv = new Ajv();
Модуль валидации я думаю стоить вынести в отдельный класс, чтобы этот interceptor ничего не знал про ajv

2020-12-28 08:56 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +  public errorHandler(errors?: any[] | null): void {
errorHandler нужно тоже будет вынести в отдельный класс, чтобы в случае чего я можно было кастомизировать

2020-12-28 08:56 UTC, KostyaZgara commented on package.json
> +    "ajv": "^7.0.2",
ajv должен быть в прямых зависимостях как и его @types/ajv (если он есть конечно)

2020-12-28 08:56 UTC, KostyaZgara commented on test/setup.ts
> +}
По-моему здесь тебе не нужны всякие setup файлы, погугли как лучше всего тестить интерсепторы. Я вот например сразу наткнулся на парочку крутых примеров.

https://stackoverflow.com/questions/57730120/how-to-test-nestjs-interceptor
https://github.com/nestjs/nest/blob/master/integration/hello-world/e2e/interceptors.spec.ts

2020-12-28 08:56 UTC, KostyaZgara commented on test/users/users.controller.ts
> +}
каждый кейс должен быть искусственным и уникальным. Это означает, что не должно быть никаких общих файлов контроллеров не должно быть. Потому что тогда уникальность каждого теста пропадает

2020-12-28 08:56 UTC, KostyaZgara commented on tsconfig.json
>  }
Почему удалил эти строки?

2020-12-28 08:56 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +  private getKeyId(context: ExecutionContext) {
не забывай про последовательность методов в классе. Начиная сверху и двигаясь вниз public => protected => private. Потом чтобы отсортировать методы одного типа, то методы которые не используются в других методах должны стоять выше. То есть

```ts
class Test {
  public first() { // I will be on the top cuz I'm not using in anywhere in this class
    this.second();
  }
  public second() { // I will be below cuz I'm using in method above
    this.third();
  }
  public third() { // I will be at the bottom cuz I'm using everywhere and I'm not using any other internal methods
    console.log('Hello world');
  }
}
```

2020-12-28 08:56 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +      this.initScheme(context);
Вот как раз таки, когда ты вынесешь `ajv` в другой класс, его можно будет заюзать в `ValidationModule` и на старте апликухе инициализировать все схемы. И дальше с помощью DI внедрить этот класс в интерсептор и тупо юзать как уже готовый сто процентов инициализированный модуль.

2020-12-28 13:57 UTC, KostyaZgara requested changes

2020-12-28 13:57 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    return next.handle();
валидации ответа нет еще

2020-12-28 13:57 UTC, KostyaZgara commented on lib/swagger-schemes.ts
> +    const schemes: any[] = [];
ты хоть бы погуглил как правильно пишется это слово или посмотрел бы как я тебе скинул название класса. Это ошибка везде

2020-12-28 13:57 UTC, KostyaZgara commented on lib/swagger-schemes.ts
> +export class SwaggerSchemes {
переименуй в `SwaggerExplorer`

2020-12-28 13:57 UTC, KostyaZgara commented on lib/swagger-schemes.ts
> +  public static getPathSchemesData(
методы не должны быть статичными. Хоть у этого класса пока что и нет состояние, но хорошим тоном в NestJS является написание классов в синглетон стиле только для одного модуля!

2020-12-28 13:57 UTC, KostyaZgara commented on lib/swagger-schemes.ts
> +          data: req[reqParam || schemaParam],
можно как-то не юзать нативный `req` объект? Есть какие-то способы достать отдельно headers, query и тд таким же образом как это сделано к контроллерах?

2020-12-28 13:57 UTC, KostyaZgara commented on lib/swagger-schemes.ts
> +}
интерфейсы должны быть описаны отдельно от реализации

2020-12-28 13:57 UTC, KostyaZgara commented on lib/validator.ts
> +});
засунь это в конструктор класса ниже

2020-12-28 13:57 UTC, KostyaZgara commented on lib/validator.ts
> +  public static boot(app: INestApplication): void {
статичные методы все надо убрать

2020-12-28 13:57 UTC, KostyaZgara commented on lib/validator.ts
> +  protected errorHandler = new ValidatorErrorHandler();
и как потом заоверрайдить этот error handler?

2020-12-28 13:57 UTC, KostyaZgara commented on lib/validator.ts
> +
в конструктор класса должна быть возможность прокидывать конфиг для ajv. Здесь тебе поможет динамические модули и DI https://docs.nestjs.com/fundamentals/dynamic-modules

2020-12-28 13:57 UTC, KostyaZgara commented on lib/validator.ts
> +export class Validator {
Создай папку в `lib` и назови её `validators`. А этот валидатор переименуй в конкретный

```suggestion
export class AjvValidator {
```

2020-12-28 13:57 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +  protected validator: Validator = new Validator();
валидатор должен прокидываться через DI (единственное я хз работает ли авто DI для глобальных интерсепторов, но в любом случае можно будет вручную сделать инъекцию) и быть инверсированным, чтобы в случае чего валидатор можно было бы подменить на любой другой. Например joi. Понятное дело, что в таком случае все валидаторы должны импелментировать один и тот же интерфейс, обязательно учти это когда будешь разделять логику. Пример как сделать валидатор независимым, можно глянуть тут https://github.com/seedium/nestjs-universal-logger/blob/9c9d2d4d2d621073010f53422f41e1ab46b1d603/lib/logger.provider.ts#L16 Здесь есть инверсия и случае чего логгер Pino можно будет заменить на любой другой, который будет имплементировать тот же интерфейс

2020-12-28 13:57 UTC, KostyaZgara commented on lib/validator-error-handler.ts
> +}
интерфейсы не здесь должны быть

2020-12-28 13:57 UTC, KostyaZgara commented on lib/swagger-schemes.ts
> +    const paths = scanner.scanApplication(app, {}).paths;
```suggestion
    const { paths } = scanner.scanApplication(app, {});
```

2020-12-28 14:05 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +    const schemes: any[] = [];
schemes => схемы https://translate.google.com/?sl=en&tl=ru&text=schemes&op=translate

2020-12-28 14:06 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +    const schemes: any[] = [];
schema => схема

2020-12-28 14:07 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +    const schemes: any[] = [];
schemas тоже схемы, но почему то гугл мне выдает schemes

2020-12-28 14:08 UTC, n1ghtm6r9 commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    return next.handle();
тут не понял

2020-12-28 14:10 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    return next.handle();
У нас должна быть валидации ответа в зависимости от статус кода. Так вот её нет, ответ не валидируется

2020-12-28 14:13 UTC, KostyaZgara commented on lib/swagger-schemes.ts
> +    const schemes: any[] = [];
Просто переименуй и все
![image](https://user-images.githubusercontent.com/18326076/103219785-54314780-4927-11eb-85df-c48d649d837a.png)

P.S. Гугл не знает об особенностях слов употребляемых в разных контекстах и специализаций. Вот поэтому существует такие словари как https://www.multitran.com/ И они во многом преобладают при профессиональном переводе

2020-12-29 09:35 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +          data: req[reqParam || schemaParam],
декораторы для контроллеров, в доках как по другому не нашел, юзают обьект req и от туда берут значения

2020-12-29 10:34 UTC, n1ghtm6r9 commented on lib/index.ts
> +export * from './interceptors/json-schema-serializer.interceptor';
+

2020-12-29 10:35 UTC, n1ghtm6r9 commented on tsconfig.json
>  }
тут потому что ide не видела tsconfig в папке с тестами, сейчас есть tsconfig.spec,  tsconfig.build

2020-12-29 10:35 UTC, n1ghtm6r9 commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +      this.initScheme(context);
+

2020-12-29 10:35 UTC, n1ghtm6r9 commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    return next.handle();
+

2020-12-29 10:36 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +    const schemes: any[] = [];
+

2020-12-29 10:37 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +export class SwaggerSchemes {
+

2020-12-29 10:37 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +  public static getPathSchemesData(
+

2020-12-29 10:37 UTC, n1ghtm6r9 commented on lib/validator.ts
> +
+

2020-12-29 10:37 UTC, n1ghtm6r9 commented on lib/validator.ts
> +export class Validator {
+

2020-12-29 10:37 UTC, n1ghtm6r9 commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +  protected validator: Validator = new Validator();
+

2020-12-29 10:37 UTC, n1ghtm6r9 commented on lib/validator-error-handler.ts
> +}
+

2020-12-29 10:38 UTC, n1ghtm6r9 commented on lib/swagger-schemes.ts
> +    const paths = scanner.scanApplication(app, {}).paths;
+

2020-12-29 11:32 UTC, KostyaZgara commented on lib/constants.ts
> +export const AJV_OPTIONS = 'AJV_OPTIONS';
Юзай лучше `Symbol.for()` они более уникальны и шанс коллизии просто отсутсвует

2020-12-29 11:32 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    private _validator: AjvValidator,
нет инверсии. Как мне в случае чего заменить Ajv на что-то другое?

2020-12-29 11:32 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    const schemasData = this._explorer.getPathSchemasData(context);
```suggestion
    const schemas = this._explorer.getPathSchemasData(context);
```

2020-12-29 11:32 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    schemasData.forEach((data) => {
```suggestion
    schemasData.forEach((schema) => {
```

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +}
что здесь делает этот интерфейс?

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +  public getPathSchemasData(context: ExecutionContext): ISchemaIdContextData[] {
```suggestion
  public getSchemaByPath(context: ExecutionContext): ISchemaIdContextData[] {
```

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +export interface ISchemaIdContextData {
```suggestion
export interface ISchemaContext {
```

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +  schemaId: string;
```suggestion
  id: string;
```

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +  data: any;
Здесь мне кажется можно же строже описать тип? Там в любом случае будут же опциональные ключи типа `body`, `query` и тд

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +          schemaId: `${controllerName}_${handlerName}_${schemaParam}`,
лучше юзать какие нибудь спец символы, если это возможно

```suggestion
          schemaId: `${controllerName}:${handlerName}:${schemaParam}`,
```

так легче будет потом сплитить, потому что метод вполне может содержать `_` и тогда про сплит можно будет забыть

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +        swaggerSchemas.parameters.forEach((s) => {
что такое `s`?

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +          const extraQueryData: any = {
избегай `any` везде, где это возможно

2020-12-29 11:32 UTC, KostyaZgara commented on lib/validation.module.ts
> +      exports: [AjvValidator, SwaggerExplorer],
`SwaggerExplorer` должен быть внутренним провайдером. Если тебе нужно инжектить его в другие места, то лучше раздели модуль на `ValidationModule` и `ValidationCoreModule` и там раздели эту логику. Пример можешь поискать все в тех же примерах

2020-12-29 11:32 UTC, KostyaZgara commented on lib/validation.module.ts
> +      ajv.addSchema(s);
почему модуль знает, что он использует `ajv` под капотом?

2020-12-29 11:32 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +});
я же вроде писал, что это должно быть в конструкторе, убери это. Ты создаешь синглтон, который потом не возможно тестировать отдельно и разделять. А что если нам нужно будет создать модуль, который вообще не должен знать про другие схемы? У нас будет только один вариант, полностью создать новый такой же модуль внутри проекта, только чтобы создать новый инстанс `ajv`

2020-12-29 11:32 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +  protected errorHandler = new ValidatorErrorHandler();
по прежнему нет инверсии для errorHandler. Как мне в приложении подменить error handler? Я хочу, чтобы это делалось легко и просто и только в одном месте

2020-12-29 11:32 UTC, KostyaZgara commented on package.json
> +    "@nestjs/platform-fastify": "^7.6.4",
а нам обязательны эти пакеты с fastify? Просто как-то странно зачем они тут нужны, если модуль должен работать одинаково на всех платформах

2020-12-29 11:32 UTC, KostyaZgara commented on tsconfig.build.json
> +}
Ничего не понимаю, почему у меня все работает с `tsconfig.json` и `tsconfig.spec.json` а тебе нужно создать отдельный `tsconfig.build.json` и модифицировать рут конфиг `tsconfig.json`? Возвращай все обратно и делай так, чтобы все работало с прежними конфигами. Может это твоя IDE не особо умная? Запускай все скрипта и смотри работает или нет. Если скрипты работают, а IDE все равно что-то не видит, то выкинь на помойку свою IDE)

2020-12-29 11:32 UTC, KostyaZgara commented on tsconfig.json
>  }
не годится

2020-12-29 11:32 UTC, KostyaZgara commented on package.json
> -    "rxjs": "^6.0.0"
а почему rxjs удалил из peerDependencies?

2020-12-29 11:32 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +        const statusCode = context.switchToHttp().getResponse().statusCode;
мне кажется нам нужен еще один какой-то класс хелпер, который будет знать эти нюансы работы с NestJS, но понятия не будет иметь какой валидатор сейчас используется и откуда пришли схемы, то ли с swagger, то ли ребята отдельно их описали.
Это касается всех общих вещей. Генерации айдишника для ajv и всего остального

2020-12-29 11:32 UTC, KostyaZgara commented on lib/swagger-explorer.ts
> +  }): any[] {
может это лучше в отдельный интерфейс?

2020-12-29 12:13 UTC, n1ghtm6r9 commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    private _validator: AjvValidator,
я так понял base класс создавать не нужно, а только интерфейс?

2020-12-29 12:25 UTC, n1ghtm6r9 commented on lib/constants.ts
> +export const AJV_OPTIONS = 'AJV_OPTIONS';
тут не понял, в другом месте я буду вызвывать Symbol.for('AJV_OPTIONS')?

2020-12-29 12:33 UTC, n1ghtm6r9 commented on tsconfig.build.json
> +}
<iframe src='//gifs.com/embed/2-vbpekB' frameborder='0' scrolling='no' width='360px' height='270px' style='-webkit-backface-visibility: hidden;-webkit-transform: scale(1);' ></iframe>

2020-12-29 12:40 UTC, KostyaZgara commented on lib/constants.ts
> +export const AJV_OPTIONS = 'AJV_OPTIONS';
нет в другом месте ты будешь импортировать этот символ и использовать его. Тут все дело в том, что каждый Symbol уникален, то есть `Symbol('test') !== Symbol('test')` таким образом и нет коллизий и можно использовать одни и те же лейблы

2020-12-29 12:41 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    private _validator: AjvValidator,
что значит base класс? Тебе нужно создать интерфейс и везде использовать интерфейс, а `AjvValidator` должен имплементировать этот интерфейс

2020-12-30 09:58 UTC, n1ghtm6r9 commented on test/setup.ts
> +}
для интеграционных нужно nestjs инициализировать что бы запросы отправлять, вторая ссылка, для юнит нет

2020-12-30 09:59 UTC, n1ghtm6r9 commented on tsconfig.json
>  }
+

2020-12-30 09:59 UTC, n1ghtm6r9 commented on tsconfig.build.json
> +}
+

2020-12-30 10:00 UTC, n1ghtm6r9 commented on package.json
> -    "rxjs": "^6.0.0"
+

2020-12-30 10:00 UTC, n1ghtm6r9 commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +        const statusCode = context.switchToHttp().getResponse().statusCode;
+

2020-12-30 10:04 UTC, n1ghtm6r9 commented on lib/swagger-explorer.ts
> +  }): any[] {
+

2020-12-30 10:31 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +      this.errorHandler.handle(validator.errors);
я тут подумал, что наверное не стоит, чтобы валидатор бросал ошибки. Здесь теряется уровень ответственности. Пускай лучше этот метод будет возвращать true or false с какими нибудь метаданными (ошибки которые сгенерил сам ajv)

2020-12-30 10:31 UTC, KostyaZgara commented on lib/interceptors/json-schema-serializer.interceptor.ts
> +    private _validator: IValidator,
```suggestion
    @Inject(VALIDATOR) private _validator: IValidator,
```

2020-12-30 10:31 UTC, KostyaZgara commented on lib/validation.module.ts
> +      exports: [AjvValidator, NestJsContextProvider, SwaggerExplorer],
SwaggerExplorer and NestJSContextProvider должны быть внутриними провайдерами. Надо разделить их с помощью двух модулей `ValidationModule` and `ValidationCoreModule`

2020-12-30 11:10 UTC, n1ghtm6r9 commented on lib/swagger-explorer.ts
> +        swaggerSchemas.parameters.forEach((s) => {
в s данные схем params query headers, переименовал в swaggerSchemasData

2021-01-05 09:49 UTC, n1ghtm6r9 commented on package.json
> +    "@nestjs/platform-fastify": "^7.6.4",
этот пакет нужен для интенграционных тестов для метода app.inject, который есть только в fastify, если отказаться от него придется юзать какой нибудь request

2021-01-05 15:21 UTC, KostyaZgara requested changes

2021-01-05 15:29 UTC, n1ghtm6r9 commented on lib/validation.module.ts
> +      ],
отсюда убрать providers и перенести в ValidationCoreModule providers? а как же параметры которые передаются с ValidationModule?

2021-01-05 15:42 UTC, n1ghtm6r9 commented on lib/swagger-explorer.ts
> +        $id: `${operationId}_body`,
swagger покажет id тот который юказал юзер, этот id для валидации, у swagger он в таком виде ControllerName_handlerName для индентификации схем по handler'у, то есть в этом обьекте есть operationId и body query, нам что бы получить нужную схему в конец нужно добавить тип данных, $id не перезатирается оно и не относиться к конкретно одной схеме

2021-01-06 09:14 UTC, KostyaZgara commented on lib/validation.module.ts
> +      ],
они должны редиректиться в `ValidationCoreModule`. Богдан, а ты точно смотришь все примеры? Просто иногда вопросы такие, которые вроде как очевидны и видны во всех примерах)

2021-01-06 09:24 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +    return schema?.schemaEnv.validate || this._ajv.compile(schema.schema);
я все равно не могу понять. Судя по докам, `getSchema` возвращает сразу скомпилинную схему
![image](https://user-images.githubusercontent.com/18326076/103751572-38a5fb00-5011-11eb-92d8-3e4df446d640.png)

То есть этот тот метод `validate` которые можно вызывать уже на данных
```ts
const validate = ajv.getSchema('some-id');
validate(data);
```
Зачем нам лезть в какие-то непонятные `schemaEnv` ради этого метода?

И второй вопрос. У нас уже есть проверка выше
```ts
if (!schema) {
  return false;
}
```
Как у нас вообще может выполниться второе условие?
```ts
this._ajv.compile(schema.schema)
```
Здесь что-то не так. По логики нихрена не сходится. Пересмотри пожалуйста это место еще раз

2021-01-06 09:45 UTC, n1ghtm6r9 commented on lib/validators/ajv-validator.ts
> +    return schema?.schemaEnv.validate || this._ajv.compile(schema.schema);
согласен, проверил, через getSchema возвращает валидатор, тот метод больше не нужен

2021-01-06 10:57 UTC, n1ghtm6r9 commented on package.json
> +    "@nestjs/platform-fastify": "^7.6.5",
вместо него будет @nestjs/platform-express, потому что это требует nestjs явно

2021-01-06 11:05 UTC, KostyaZgara commented on package.json
> +    "@nestjs/platform-fastify": "^7.6.5",
ну окей. Пусть будет так. Но еще раз повторюсь. Проверку всех кейсов должно быть через юнит тесты. Интеграционных должно быть штук 5 от силы. Проверить, что interceptor отрабатывает при запросе и при ответе и возможно еще пару кейсов, все остальное должно проверяться через юнит тесты отдельно друг от друга. Поэтому какая платформа и не должно быть важно

2021-01-07 13:13 UTC, KostyaZgara requested changes

2021-01-07 13:13 UTC, KostyaZgara commented on test/json-schema-serializer.interceptor.spec.ts
> +    };
я думаю, что interceptor лучше тестировать интеграционными тестами, чтобы так не извращаться

2021-01-07 13:13 UTC, KostyaZgara commented on test/json-schema-serializer.interceptor.spec.ts
> +      };
ну нельзя все в одном кейсе тестировать. Разбей это на 4 разных кейса, где отдельно проверяешь, что правильно валидируется `body`, `query` и тд

2021-01-07 13:13 UTC, KostyaZgara commented on test/validation.spec.ts
> +    .valueOf();
не должно быть никаких глобальных общих схем. Каждый кейс должен быть сугубо уникальным! Если все кейсы использует все одинаковое, тогда мы по сути тестируем один кейс. И это не означает, что теперь для каждого кейса, нужно просто разные схемы задавать, нет. Смысл в том, что нужно проверить конкретно определенное поведение. Например `should validate integer`, `should validate array` и тд.

2021-01-07 13:13 UTC, KostyaZgara commented on test/validation.spec.ts
> +    });
вот что конкретно нашего ты здесь тестируешь? Трансформацией объекта занимается `ajv` и по сути ты только что написал тест для `ajv` а не для нашего модуля

2021-01-07 13:13 UTC, KostyaZgara commented on test/validation.spec.ts
> +import {
Теперь осталось написать тесты, чтобы добиться покрытие кода 100%.
Интересптор можно протестировать интеграционными тестами, а значит там допускается `app.init()` а все остальное только юнит тестами

2021-01-07 13:32 UTC, n1ghtm6r9 commented on lib/services/swagger-explorer.service.ts
> +    const filterQuery = (f) => f.in === 'query';
привычка из прошлого, обычно циклические переменные так обозначали

2021-01-08 12:09 UTC, KostyaZgara requested changes

2021-01-08 12:09 UTC, KostyaZgara commented on test/validation.spec.ts
> +import S from 'fluent-schema';
не совсем то. Смотри, просто и бездумно добивать 100% покрытия не имеет большого смысла. Гнаться за цифрами в ущерб логики не надо. Поэтому предлагаю тебе следующий план.
1. В папке `test` создай файлы `json-schema-serializer-interceptor.spec.ts`, `swagger-explorer-service.spec.ts`, `ajv-validator.spec.ts`, `validation-module.spec.ts`.
2. В файле `json-schema-serializer-interceptor.spec.ts` у тебя будут парочку интеграционных тестов, а именно тебе нужно проверить вызывается ли корректно метод `intercept`. Срабатывает ли `next.handle().pipe()` корректно на ответе, ну и плюс я думаю можно выдумать и попроверять типа правильно ли он ищет схемы для всех статус кодов. Корректно ли он ищет данные в реквесте (query, params, headers). Причем тебе не надо проверять бизнес логику, тебе нужно проверить только факт корректно ли вызвался метод или нет. То есть каждый твой кейс будет сводиться к тому, что ты описываешь схему и тестируешь к примеру `query`. И ты просто мокаешь или спаишь определенные функции и потом смотришь, что они вернули и сравниваешь это с ожидаемым ответом. Проверить прям правильно свалидировал или нет, не надо! Это уже пускай ребята из AJV делают тесты на правильность валидации
3. `swagger-explorer-service.spec.ts` будет содержать уже только юнит тесты. Здесь все просто кажды раз компилишь новый модуль `Test.createTestingModule()` и проверяешь отдельно каждый кейс в виде правильно ли он забрал swagger схему для ApiParam, ApiHeader и тд. В общем делаешь все, чтобы юнит тестами дернуть каждую строчку кода в сервисе
4. `ajv-validator.spec.ts` здесь тоже все очень просто. Просто мокаешь `_ajv` и смотришь корректные ли методы вызываются при вызове наших методов в `AjvValidator`
5. `validation-module.spec.ts` ну и здесь тоже должно быть все предельно просто. Здесь также юнит тесты и нужно проверить правильно ли предаются параметры, подменяются ли кастомные errorHandler в общем всю логику, которую содержит модуль нужно протестировать. А ну и плюс здесь же можно проверить метод `onApplicationBootstrap` и буквально создать один кейс, чтобы удостовериться, что он умеет забирать хотя бы одну схему и добавлять в `AjvValidator`. То есть здесь даже `AjvValidator` можно замокать, нам не важно корректно ли он отправил это все в `ajv` потому что этот кейс мы уже проверили в другом месте и знаем точно, что при вызове `loadSchemas` `AjvValidator` корректно передает это в `ajv`

2021-01-08 12:10 UTC, KostyaZgara commented on test/validation.spec.ts
> +  }
```suggestion
  async function createApp(controller): Promise<INestApplication> {
    const moduleRef = await Test.createTestingModule({
      imports: [ValidationModule.forRoot()],
      controllers: [controller],
    }).compile();

    app = moduleRef.createNestApplication();

    const ajvValidator = app.get(VALIDATOR);
    const errorHandler = app.get(VALIDATOR_ERROR_HANDLER);

    app.useGlobalInterceptors(
      new JsonSchemaSerializerInterceptor(ajvValidator, errorHandler),
    );

    app.useGlobalFilters(new CustomExceptionFilter());

    await app.init();
    return app;
  }
```

2021-01-11 10:32 UTC, KostyaZgara requested changes

2021-01-11 10:32 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +  public setUpAjv(options?: Options): void {
не не) Так не подходит) Я так понимаю это сделано ради того, чтобы можно было заспаить опции, но это плохо влияет на UX и понимание класса. Чтобы заспаить опции для ajv, есть другой вариант. Я юзал вот эту библу https://github.com/thlorenz/proxyquire чтобы замокать зависимость и проверить все что надо. Но последнее время я в смятении с этим решением и в большинстве случаев я просто это не тестирую, за исключением тех случаев, когда опции как-то модифицируется во время работы программы и их жизненно важно проверить, но тогда для этого и нужны внутренние методы типа `buildOptions`. В общем решать тебе какой вариант выбрать)

2021-01-11 10:32 UTC, KostyaZgara commented on test/ajv-validator.spec.ts
> +    sinon.replace(Ajv.prototype, 'getSchema', fakeGetSchema);
По-моему вот так лучше читается и меньше пишется.

```suggestion
    const stubGetSchema = sinon.stub(Ajv.prototype, <any>'getSchema').returns(false);
```

только чекни синтаксис! Мог ошибиться

2021-01-11 10:32 UTC, KostyaZgara commented on test/ajv-validator.spec.ts
> +    ajvValidator = new AjvValidator();
Я смотрю ниже много где моканье прототипа, а это не самый лучший подход, потому что ты мокаешь глобальный прототип, а мы тестируем только `Ajv` который в классе `AjvValidator`. Я предлагаю тебе сделать псевда глобальный мок для удобства

```suggestion
  let ajvValidator: AjvValidator;
  let mockAjv: sinon.SinonMock;

  beforeEach(() => {
    ajvValidator = new AjvValidator();
    mockAjv = sinon.mock((ajvValidator as any)._ajv);
```

и дальше в каждом кейсе делать примерно так
```ts
it('should be success result if schema not exist', async () => {
    mockAjv.expects('getSchema').returns(false);
    mockAjv.expects('getSchema').once().called();
    const result = await ajvValidator.validateById('', {});
    expect(result.success).is.true;
    mockAjv.verify();
  });
```
Только опять же таки чекни синтаксис, пишу все по памяти

2021-01-11 10:32 UTC, KostyaZgara commented on test/json-schema-serializer-interceptor.spec.ts
> +  }
```suggestion
  async function createApp(controller): Promise<INestApplication> {
    const moduleRef = await Test.createTestingModule({
      imports: [ValidationModule.forRoot()],
      controllers: [controller],
    }).compile();

    app = moduleRef.createNestApplication();
    const ajvValidator = app.get(VALIDATOR);
    const errorHandler = app.get(VALIDATOR_ERROR_HANDLER);

    app.useGlobalInterceptors(
      new JsonSchemaSerializerInterceptor(ajvValidator, errorHandler),
    );

    app.useGlobalFilters(new CustomExceptionFilter());
    await app.init();

    return app;
  }
```

Так я же не зря тебе написал добавить `return app`; Здесь ты делаешь app глобальным и в случае добавления флага `--parallel` для увечичения скорости, все сломается. Лучше этот app делать либо в каждом кейсе, либо в ближайшем `beforeEach`

```ts
desribe('root, () => {
  async function createApp() {
    return app;
  }
  describe('params, () => {
    let app: INestApplication;
    beforeEach(async () => {
      app = await createApp();
    })
  })
})
```

2021-01-11 10:32 UTC, KostyaZgara commented on test/json-schema-serializer-interceptor.spec.ts
> +      const spyValidateById = sinon.spy(AjvValidator.prototype, 'validateById');
Не надо мокать, спаить или стабить прототипы. Только прям в крайней случае, когда нам нужно мокнуть чужую зависимость и другого выхода нет. Но это всё наши зависимости и их инстансы можно легко сохранить или вытащить, чтобы потом замокать. Опять же таки, просто думай, что в этот момент происходит, а происходит то, что мы стремимся изолировать код как можно сильней с помощью композиции, DI и других техник, но тестируем код так будто у нас до сих пор глобальные синглетоны

2021-01-11 10:32 UTC, KostyaZgara commented on test/swagger-explorer-service.spec.ts
> +    sinon.restore();
по-моему это должно быть в другом месте

2021-01-11 10:32 UTC, KostyaZgara commented on test/swagger-explorer-service.spec.ts
> +      });
а можно это как-то по красивее сделать не используя индексы для массива?)

2021-01-11 10:32 UTC, KostyaZgara commented on test/swagger-explorer-service.spec.ts
> +    await app.init();
а попробуй без этого
```suggestion
```

Здесь тебе надо, чтобы вызвался `onApplicationBootstrap` но у меня есть чуйка, что он вызывается еще на этапе `.compile()`

2021-01-11 10:32 UTC, KostyaZgara commented on test/validation-module.spec.ts
> +    const app = moduleRef.createNestApplication();
ну вот здесь тебе точно это не надо. Инжектирование классов точно происходит на этапе `.compile()`
```suggestion
```

2021-01-11 10:32 UTC, KostyaZgara commented on test/validation-module.spec.ts
> +    });
Избегай `.replace()`. Тебе в 95% случаев должно хватать обычного `sinon.stub()`.

2021-01-11 10:32 UTC, KostyaZgara commented on validation.spec.ts
> +import S from 'fluent-schema';
а це що такэ?)

2021-01-11 12:11 UTC, n1ghtm6r9 commented on test/swagger-explorer-service.spec.ts
> +    await app.init();
не работает без этого

2021-01-11 12:27 UTC, KostyaZgara requested changes

2021-01-11 12:27 UTC, KostyaZgara commented on test/json-schema-serializer-interceptor.spec.ts
> +      });
здесь еще `.replace` остался. Поищи пожалуйста в других местах на всякий случай

2021-01-11 12:50 UTC, n1ghtm6r9 commented on test/json-schema-serializer-interceptor.spec.ts
> +      });
этот убрал, там остался один, но в нем логика прописана, так что он нужен

2021-01-11 12:57 UTC, KostyaZgara commented on test/json-schema-serializer-interceptor.spec.ts
> +      });
Какая логика? Любую логику можно прописать в стаб методе `callsFake` и то не стоит злоупотреблять этим методом. Все таки не забывай, что такое юнит тестирование. Никакой бизнес логики не должно быть. Должны быть входные значение и ожидаемые выходные. Когда употребляется слово ожидаемый то практически всегда имеют ввиду использование литеральных объектов. Если невозможно предугадать, что будет на выходе, значит надо подумать еще раз правильно ли это утверждение и возможно ты не до конца понял как надо тестировать, либо второй вариант, который очень важен. Значит функция не поддает тестирование, а в этом случае нужно бить тревогу и переписывать куски кода так, чтобы они имели предсказуемое поведение их можно было проверить юнит тестами.

2021-01-13 08:26 UTC, KostyaZgara requested changes

2021-01-13 08:26 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +  }
Ну в принципе это то, что мы с тобой и обсуждали, только я хотел сделать отдельно 2 метода. Для загрузки схем без всяких префиксов и с префиксом. Именно поэтому должно быть 2 метода. А так получается, что мы никак не сможем загрузить схемы без префикса. Давай сделаем так

```ts
public loadSchema(schema) {
  this.ajv.addSchema(schema);
}
public loadSwaggerSchema(schemas) {
  schemas.forEach((schema) => {
    schema = {
       ...schema,
       required: // add required,
      $async: true,
    }
    schema = this.addPrefixToRefs(VALIDATOR_ID_PREFIX, shcema);
    if (schema.$id) {
      schema.$id = `${VALIDATOR_ID_PREFIX}${schema.$id}`;
    }
    this.ajv.addSchema(schema);
  })
}
```

2021-01-13 08:26 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +    const validator = this._ajv.getSchema(`${VALIDATOR_ID_PREFIX}${schemaId}`);
И здесь получается нужно то же 2 метода. Предлагаю сделать `validateBySchemaId` (для обычных схем без префикса) и `validateBySwaggerSchemaId`

2021-01-13 08:32 UTC, n1ghtm6r9 commented on lib/validators/ajv-validator.ts
> +  }
наши схемы мы будем загружать через метод loadSwaggerSchema?

2021-01-13 08:33 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +  }
Не совсем понимаю какие наши?) Они вроде все наши)

2021-01-13 08:34 UTC, n1ghtm6r9 commented on lib/validators/ajv-validator.ts
> +  }
по типу Timestamp он же с id #/components/schemas/Timestamp будет идти

2021-01-13 08:36 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +  }
я честно не понимаю твоего вопроса. Ты же сделал эти манипуляции с префиксами? Значит как-то видел, что это можно сделать. Все что я сделал это просто отрефакторил эти методы и сделал их независимыми, функционал я не менял

2021-01-13 11:11 UTC, n1ghtm6r9 commented on lib/validators/ajv-validator.ts
> +    const validator = this._ajv.getSchema(`${VALIDATOR_ID_PREFIX}${schemaId}`);
если идет разделения методов validateBySchemaId, validateBySwaggerSchemaId, то у нас все равно валидация асинхронная, поэтому поле $async: true обязательно даже в loadSchema, иначе если не будет этого поля validateBySchemaId не выбросит ошибку

2021-01-13 11:13 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +    const validator = this._ajv.getSchema(`${VALIDATOR_ID_PREFIX}${schemaId}`);
та окей. Я же тебе не запрещаю, добавишь и туда и туда

2021-01-13 12:54 UTC, KostyaZgara commented on lib/services/swagger-explorer.service.ts
> +      return JSON.parse(JSON.stringify(schemas));
а это для чего?

2021-01-13 12:54 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +      if (schema.required === true) {
а тебе прям проверки на true надо делать или можно на truly? То есть может вот так будет лучше?

```suggestion
      if (schema.required) {
```

2021-01-13 12:54 UTC, KostyaZgara commented on lib/validators/ajv-validator.ts
> +      if (typeof schema[key] === 'object') {
здесь безопаснее будет сделать конкретно проверку на объект, потому что если ты помнишь, то `typeof [] === 'object` будет тоже `true`.

2021-01-13 12:54 UTC, KostyaZgara commented on test/ajv-validator.spec.ts
> +    it('should be change ref', async () => {
```suggestion
    it('should change ref', async () => {
```

2021-01-13 12:59 UTC, n1ghtm6r9 commented on lib/services/swagger-explorer.service.ts
> +      return JSON.parse(JSON.stringify(schemas));
рекурсия меняет память обьекта swagger, тут либо рекурсию переделывать либо всегда копию возвращать что бы в будущем никогда нельзя было изменить оригинальный обьект схем

2021-01-13 13:00 UTC, n1ghtm6r9 commented on lib/validators/ajv-validator.ts
> +      if (schema.required === true) {
там именно true, потому что может быть массив и он тоже является == true

2021-01-13 13:24 UTC, KostyaZgara commented on lib/services/swagger-explorer.service.ts
> +      return JSON.parse(JSON.stringify(schemas));
Оставляй комментарии на такие случаи

2021-03-05 11:10 UTC, KostyaZgara submitted a review, later dismissed
LGFFT (looks good for first time)
I think some refactoring is a need in a future

2021-03-05 11:26 UTC, KostyaZgara approved these changes
LGFFT (looks good for first time)

2021-03-05 11:27 UTC, merged